config/routes.rb
Rails.application.routes.draw do
  root "artists#index"

  resources :artists, except: [:new, :edit, :create, :update] do
      resources :songs, except: [:edit, :update]
  end

  namespace :api do
    resources :artists, only: [:index, :show] do
        resources :songs, except: [:edit, :update]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  has_one :photo, dependent: :destroy

  validates :name, presence: true
  validates :birth_date, presence: true
  validates :country_of_origin, presence: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :artist
  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  validates :name, presence: true
end

app/controllers/api/artists_controller.rb
class Api::ArtistsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    render status: 200, json: Artist.all
  end

  def show
  artist = Artist.find(params[:id])
  render status: 200, json: artist
end
end

app/controllers/api/songs_controller.rb
class Api::SongsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_artist
  def index
    render status: 200, json: @artist.songs
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy

    render status: 200, json: {
      message: "Room successfully deleted"
    }.to_json
  end


  def create
    song = @artist.songs.new(song_params)

    if song.save
      render status: 200, json: {
        message: "Song successfully created",
        artist: @artist,
        song: song
      }.to_json
    else
      render status: 422, json: {
        message: "Song could not be created",
        errors: song.errors
      }.to_json
    end
  end

  def destroy
    song = @artist.songs.find(params[:id])
    song.destroy

    render status: 200, json: {
      message: "song successfully deleted"
    }.to_json
  end
  private

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

  def song_params
    params.require(:song).permit(:name, :release_date, :genre)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end
  def show
    @artist = Artist.find(params[:id])
  end
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to root_url, notice: "Artist succesfully removed"
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    before_action :load_artist

    def show
      @song = @artist.songs.find(params[:id])
    end
    
    def new
      @song = @artist.songs.new
    end

    def create
      @song = @artist.songs.new(song_params)

      if @song.save
        redirect_to @artist, notice: "song created"
      else
        render :new
      end
    end

    def destroy
      song = @artist.songs.find(params[:id])
      song.destroy
      redirect_to artist_path(@artist), notice: "Song succesfully removed"
    end

    private

    def load_artist
      @artist = Artist.find(params[:artist_id])
    end

    def song_params
      params.require(:song).permit(:name, :release_date, :genre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for [@artist, @artist.songs.new] do |f| %>
  <div class="form-group">
    <label>Name</label>
    <%= f.text_field :name, placeholder: "Name", class: "form-control" %>
  </div>

  <label>Add this song?</label>

  <div class="actions">
    <%= f.submit "Add song", class: "btn btn-primary", data: {disable_with: false}%>
  </div>
<% end %>

app/views/artists/index.html.erb
<div class="panel panel-primary text-center container-fluid">
  <div class="panel-heading">
    <h1>All artists:</h1>
  </div>
  <div class="panel-body">

    <% @artists.each do |artist| %>
    <div class="list-group">
      <div class="list-group-item">
        <h4><%= link_to "#{artist.name}", artist%></h4>
        <%= image_tag artist.photo.image.thumbnail, class: :image_responsive %>
      </div>
      <%= link_to "Delete artist", artist, class: "btn btn-default", method: :delete, data: { confirm: "Are you sure?" } %>
    </div>
    <% end %>

  </div>
</div>

app/views/artists/show.html.erb
<h1><%=@artist.name%></h1>

<h3>All songs</h3>

<ol id="song_list">
  <% @artist.songs.each do |song|%>
    <li class="song", id="<%= song.id %>"> <%= song.name %>
      <%= link_to "Delete song", artist_song_path(@artist, song), id: song.id, class: "btn btn-primary delSong" %>
    </li>
  <% end %>
</ol>
<a id="delAllSongs", class="btn btn-primary", href="#">Delete all songs</a>

<hr>
<%= render "form"%>

<hr>

<input type="hidden" id="artist_id" value="<%= @artist.id %>">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.min.js' %>
  </head>

  <body>
    <%= yield %>
    <hr>
    <%= link_to "[All artists]", root_url %>
  </body>
</html>

app/views/songs/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add a new song
  </div>


  <%= form_for [@artist, @artist.songs.new] do |f| %>
    <div class="form-group">
      <label>Name</label>
      <%= f.text_field :name, placeholder: "Name", class: "form-control" %>
    </div>

    <div class="form-group">
      <label>Genre</label>
      <%= f.text_field :genre, placeholder: "Genre", class: "form-control" %>
    </div>


    <div class="form-group">
      <label>Release Date</label>
      <%=  f.date_select :release_date, class: "form-control" %>
    </div>

    <label>Add this song?</label>

    <div class="actions">
      <%= f.submit "Save", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/songs/show.html.erb
<h1>playing song: <%=@song.name%></h1>
<ul>
  <li>Artist: <%=@song.artist.name%></li>
  <li>Genre: <%=@song.genre%></li>
  <li>release_date: <%=@song.release_date%></li>
</ul>

<%= link_to "Back to artist", artist_path(@song.artist), class: "btn btn-primary" %>
<%= link_to "Delete song", artist_song_path([@song.artist, @song]), class: "btn btn-default", method: :delete, data: { confirm: "Are you sure?" } %>